-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 22:44:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cartola`;
USE `cartola` ;

-- -----------------------------------------------------
-- Table `mydb`.`Liga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Liga` (
  `idLiga` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Times` VARCHAR(500) NULL,
  PRIMARY KEY (`idLiga`));
-- -----------------------------------------------------
-- Table `mydb`.`Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Time` (
  `idTime` INT NOT NULL,
  `Jogadores` VARCHAR(500) NULL,
  `Pontuacao` FLOAT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Dinheiro` FLOAT NOT NULL,
  `Liga_idLiga` INT,
  PRIMARY KEY (`idTime`),
  CONSTRAINT `fk_Time_Liga1`
    FOREIGN KEY (`Liga_idLiga`)
    REFERENCES `Liga` (`idLiga`)
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`Jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jogador` (
  `idJogador` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Time` VARCHAR(45),
  `Pontuacao` FLOAT NULL,
  `Preco` FLOAT NOT NULL,
  `Posicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idJogador`));

-- -----------------------------------------------------
-- Table `mydb`.`Jogador_has_Time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Jogador_has_Time` (
  `Jogador_idJogador` INT NOT NULL,
  `Time_idTime` INT NOT NULL,
  PRIMARY KEY (`Jogador_idJogador`, `Time_idTime`),
  CONSTRAINT `fk_Jogador_has_Time_Jogador`
    FOREIGN KEY (`Jogador_idJogador`)
    REFERENCES `Jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogador_has_Time_Time1`
    FOREIGN KEY (`Time_idTime`)
    REFERENCES `Time` (`idTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    select * from Jogador;
    select * from Time;
    select * from Liga;
    
